[package]
name = "http-gateway-verifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.18"
ic-certified-assets = "0.3"

serde = "1.0"
serde_bytes = "0.11"

sev = { version = "6.2.1", default-features = false, features = [
  "crypto_nossl",
  "snp",
] }
anyhow = "1.0"
x509-parser = { version = "0.16.0", features = ["verify"] }

num-traits = "0.2"

# We need this to override the system random number generator, which is not available in the canister.
getrandom = { version = "0.2", features = ["custom"] }
